# Generated by Django 4.2.3 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='image',
            field=models.ImageField(blank=True, default='images/default_study_plan.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default_user.jpg', null=True, upload_to='images/'),
        ),
    ]
