# Generated by Django 4.2.3 on 2024-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0002_alter_question_distractors"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="topics_to_revisit",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="context",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="question",
            name="feedback",
            field=models.TextField(default=""),
        ),
    ]
