# Generated by Django 4.2.3 on 2024-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0003_quiz_topics_to_revisit_alter_question_context_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="topics_to_revisit",
            field=models.JSONField(null=True),
        ),
    ]
