# Generated by Django 4.2.3 on 2023-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0003_alter_studyplan_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='fypbackend.book'),
        ),
    ]
