# Generated by Django 4.2.3 on 2023-11-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0004_alter_studyplan_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerspost',
            name='isreply',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='answerspost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='fypbackend.querypost'),
        ),
    ]
