# Generated by Django 4.2.3 on 2024-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0004_alter_quiz_topics_to_revisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="distractors",
            field=models.JSONField(null=True),
        ),
    ]
