# Generated by Django 4.2.3 on 2024-04-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0005_alter_question_distractors"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
