# Generated by Django 4.2.3 on 2024-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0006_question_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="total_versions",
            field=models.IntegerField(default=0),
        ),
    ]
