# Generated by Django 4.2.3 on 2023-12-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0006_remove_book_author_remove_book_publication_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='description',
            new_name='current_academic_level',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='members',
            field=models.ManyToManyField(null=True, related_name='joined_studyplan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subject',
            field=models.TextField(default='Physics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_study_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
