# Generated by Django 4.2.3 on 2023-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0007_rename_description_studyplan_current_academic_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='current_academic_level',
            new_name='academic_level',
        ),
    ]
