# Generated by Django 4.2.3 on 2023-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0010_studyplan_quizesperweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklygoals',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklygoals',
            name='is_started',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='weeklygoals',
            name='topics_covered',
            field=models.ManyToManyField(blank=True, related_name='covered_in_weekly_goals', to='fypbackend.chapter'),
        ),
        migrations.AlterField(
            model_name='weeklygoals',
            name='topics_to_be_covered',
            field=models.ManyToManyField(blank=True, related_name='planned_in_weekly_goals', to='fypbackend.chapter'),
        ),
    ]
