# Generated by Django 4.2.3 on 2023-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0011_alter_weeklygoals_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygoals',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
