# Generated by Django 4.2.3 on 2024-01-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0012_weeklygoals_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querypost',
            name='title',
        ),
    ]
