# Generated by Django 4.2.3 on 2024-01-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0013_remove_querypost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.TextField(null=True),
        ),
    ]
