# Generated by Django 4.2.3 on 2024-01-12 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0014_remove_user_location_user_city_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('is_mcq', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('Topicses', models.ManyToManyField(blank=True, null=True, to='fypbackend.topic')),
                ('members', models.ManyToManyField(null=True, related_name='joined_quizroom', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_quizroom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
