# Generated by Django 4.2.3 on 2024-01-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackend', '0015_quizroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
