# Generated by Django 4.2.3 on 2024-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0018_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizroom",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="quizroom",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
