# Generated by Django 4.2.3 on 2024-02-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0019_quizroom_date_quizroom_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizroom",
            name="StudyPlan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizroom",
                to="fypbackend.studyplan",
            ),
            preserve_default=False,
        ),
    ]
