# Generated by Django 4.2.3 on 2024-02-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0020_quizroom_studyplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizroom",
            old_name="StudyPlan",
            new_name="study_plan",
        ),
    ]
