# Generated by Django 4.2.3 on 2024-02-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0021_rename_studyplan_quizroom_study_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklygoals",
            name="user",
            field=models.ForeignKey(
                default=36,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
