# Generated by Django 4.2.3 on 2024-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0022_weeklygoals_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklygoals",
            name="topics_covered",
            field=models.ManyToManyField(
                blank=True,
                related_name="covered_in_weekly_goals",
                to="fypbackend.topic",
            ),
        ),
        migrations.AlterField(
            model_name="weeklygoals",
            name="topics_to_be_covered",
            field=models.ManyToManyField(
                blank=True,
                related_name="planned_in_weekly_goals",
                to="fypbackend.topic",
            ),
        ),
    ]
