# Generated by Django 4.2.3 on 2024-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0024_topic_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklygoals",
            name="all_topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="alltopics_in_weekly_goals",
                to="fypbackend.topic",
            ),
        ),
    ]
