# Generated by Django 4.2.3 on 2024-03-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0025_weeklygoals_all_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="City",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Country",
        ),
    ]
