# Generated by Django 4.2.3 on 2024-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fypbackend", "0026_remove_user_city_remove_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
